# `cd` to here
# then `docker-compose create`

version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 33006:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nmpcdmini
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./../src:/var/www/nmpcd
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
#    image: php:7-fpm
    build: .
    restart: always
    volumes:
      - ./../src:/var/www/nmpcd

volumes:
  db_data: